version: "3.8"

services:
  timelapse-camera:
    container_name: timelapse-camera
    image: timelapse-camera:latest
    build: .
    restart: unless-stopped
    volumes:
      - ./app/static:/app/static
    ports:
      - "8000:8000"
    devices:
      - "/dev/video0:/dev/video0"  # Attach Raspberry Pi camera
      - "/dev/vchiq:/dev/vchiq"  # Grants access to the Raspberry Pi camera module
    environment:
      - CAPTURE_DEVICE=/dev/video0  # Define capture device
